version: '3.9'

services:
  api:
    build: ./
    container_name: node-api
    ports:
      - ${PORT}:${PORT}
    volumes:
      - nodeModule:/app/node_modules
      - .:/app
    depends_on:
      - cache
    links:
      - db

  db:
    image: mysql
    container_name: mysql-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_DEV_PWD}
      MYSQL_DATABASE: ${DB_DEV_NAME}
      MYSQL_PASSWORD: ${DB_DEV_PWD}
    volumes:
      - dbdata:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    links:
      - db
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${DB_DEV_PWD}
    restart: always
    depends_on:
      - db
    
volumes:
  dbdata:
  nodeModule: